language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build shortcut_client_ruby.gemspec
  - gem install ./shortcut_client_ruby-0.1.2.gem
