# -*- encoding: utf-8 -*-

=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "shortcut_client_ruby/version"

Gem::Specification.new do |s|
  s.name        = "shortcut_client_ruby"
  s.version     = Shortcut::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["ngouy"]
  s.email       = ["nathangouy@free.fr"]
  s.homepage    = "https://github.com/ngouy/shortcut_client_ruby"
  s.summary     = "Shortcut API Ruby Gem"
  s.description = "Shortcut API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
