=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module Shortcut
  # A group of calculated values for this Label. This is not included if the slim? flag is set to true for the List Labels endpoint.
  class LabelStats
    # The total number of Documents associated this Label.
    attr_accessor :num_related_documents

    # The total number of Epics with this Label.
    attr_accessor :num_epics

    # The total number of stories unstarted Stories with this Label.
    attr_accessor :num_stories_unstarted

    # The total number of Stories with this Label.
    attr_accessor :num_stories_total

    # The number of unstarted epics assoicated with this label.
    attr_accessor :num_epics_unstarted

    # The number of in progress epics assoicated with this label.
    attr_accessor :num_epics_in_progress

    # The total number of unstarted points with this Label.
    attr_accessor :num_points_unstarted

    # The total number of Stories with no point estimate with this Label.
    attr_accessor :num_stories_unestimated

    # The total number of in-progress points with this Label.
    attr_accessor :num_points_in_progress

    # The total number of Epics assoicated with this Label.
    attr_accessor :num_epics_total

    # The total number of completed Stories with this Label.
    attr_accessor :num_stories_completed

    # The total number of completed points with this Label.
    attr_accessor :num_points_completed

    # The total number of points with this Label.
    attr_accessor :num_points_total

    # The total number of in-progress Stories with this Label.
    attr_accessor :num_stories_in_progress

    # The number of completed Epics assoicated with this Label.
    attr_accessor :num_epics_completed

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'num_related_documents' => :'num_related_documents',
        :'num_epics' => :'num_epics',
        :'num_stories_unstarted' => :'num_stories_unstarted',
        :'num_stories_total' => :'num_stories_total',
        :'num_epics_unstarted' => :'num_epics_unstarted',
        :'num_epics_in_progress' => :'num_epics_in_progress',
        :'num_points_unstarted' => :'num_points_unstarted',
        :'num_stories_unestimated' => :'num_stories_unestimated',
        :'num_points_in_progress' => :'num_points_in_progress',
        :'num_epics_total' => :'num_epics_total',
        :'num_stories_completed' => :'num_stories_completed',
        :'num_points_completed' => :'num_points_completed',
        :'num_points_total' => :'num_points_total',
        :'num_stories_in_progress' => :'num_stories_in_progress',
        :'num_epics_completed' => :'num_epics_completed'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'num_related_documents' => :'Integer',
        :'num_epics' => :'Integer',
        :'num_stories_unstarted' => :'Integer',
        :'num_stories_total' => :'Integer',
        :'num_epics_unstarted' => :'Integer',
        :'num_epics_in_progress' => :'Integer',
        :'num_points_unstarted' => :'Integer',
        :'num_stories_unestimated' => :'Integer',
        :'num_points_in_progress' => :'Integer',
        :'num_epics_total' => :'Integer',
        :'num_stories_completed' => :'Integer',
        :'num_points_completed' => :'Integer',
        :'num_points_total' => :'Integer',
        :'num_stories_in_progress' => :'Integer',
        :'num_epics_completed' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shortcut::LabelStats` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shortcut::LabelStats`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'num_related_documents')
        self.num_related_documents = attributes[:'num_related_documents']
      end

      if attributes.key?(:'num_epics')
        self.num_epics = attributes[:'num_epics']
      end

      if attributes.key?(:'num_stories_unstarted')
        self.num_stories_unstarted = attributes[:'num_stories_unstarted']
      end

      if attributes.key?(:'num_stories_total')
        self.num_stories_total = attributes[:'num_stories_total']
      end

      if attributes.key?(:'num_epics_unstarted')
        self.num_epics_unstarted = attributes[:'num_epics_unstarted']
      end

      if attributes.key?(:'num_epics_in_progress')
        self.num_epics_in_progress = attributes[:'num_epics_in_progress']
      end

      if attributes.key?(:'num_points_unstarted')
        self.num_points_unstarted = attributes[:'num_points_unstarted']
      end

      if attributes.key?(:'num_stories_unestimated')
        self.num_stories_unestimated = attributes[:'num_stories_unestimated']
      end

      if attributes.key?(:'num_points_in_progress')
        self.num_points_in_progress = attributes[:'num_points_in_progress']
      end

      if attributes.key?(:'num_epics_total')
        self.num_epics_total = attributes[:'num_epics_total']
      end

      if attributes.key?(:'num_stories_completed')
        self.num_stories_completed = attributes[:'num_stories_completed']
      end

      if attributes.key?(:'num_points_completed')
        self.num_points_completed = attributes[:'num_points_completed']
      end

      if attributes.key?(:'num_points_total')
        self.num_points_total = attributes[:'num_points_total']
      end

      if attributes.key?(:'num_stories_in_progress')
        self.num_stories_in_progress = attributes[:'num_stories_in_progress']
      end

      if attributes.key?(:'num_epics_completed')
        self.num_epics_completed = attributes[:'num_epics_completed']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @num_related_documents.nil?
        invalid_properties.push('invalid value for "num_related_documents", num_related_documents cannot be nil.')
      end

      if @num_epics.nil?
        invalid_properties.push('invalid value for "num_epics", num_epics cannot be nil.')
      end

      if @num_stories_unstarted.nil?
        invalid_properties.push('invalid value for "num_stories_unstarted", num_stories_unstarted cannot be nil.')
      end

      if @num_stories_total.nil?
        invalid_properties.push('invalid value for "num_stories_total", num_stories_total cannot be nil.')
      end

      if @num_epics_unstarted.nil?
        invalid_properties.push('invalid value for "num_epics_unstarted", num_epics_unstarted cannot be nil.')
      end

      if @num_epics_in_progress.nil?
        invalid_properties.push('invalid value for "num_epics_in_progress", num_epics_in_progress cannot be nil.')
      end

      if @num_points_unstarted.nil?
        invalid_properties.push('invalid value for "num_points_unstarted", num_points_unstarted cannot be nil.')
      end

      if @num_stories_unestimated.nil?
        invalid_properties.push('invalid value for "num_stories_unestimated", num_stories_unestimated cannot be nil.')
      end

      if @num_points_in_progress.nil?
        invalid_properties.push('invalid value for "num_points_in_progress", num_points_in_progress cannot be nil.')
      end

      if @num_epics_total.nil?
        invalid_properties.push('invalid value for "num_epics_total", num_epics_total cannot be nil.')
      end

      if @num_stories_completed.nil?
        invalid_properties.push('invalid value for "num_stories_completed", num_stories_completed cannot be nil.')
      end

      if @num_points_completed.nil?
        invalid_properties.push('invalid value for "num_points_completed", num_points_completed cannot be nil.')
      end

      if @num_points_total.nil?
        invalid_properties.push('invalid value for "num_points_total", num_points_total cannot be nil.')
      end

      if @num_stories_in_progress.nil?
        invalid_properties.push('invalid value for "num_stories_in_progress", num_stories_in_progress cannot be nil.')
      end

      if @num_epics_completed.nil?
        invalid_properties.push('invalid value for "num_epics_completed", num_epics_completed cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @num_related_documents.nil?
      return false if @num_epics.nil?
      return false if @num_stories_unstarted.nil?
      return false if @num_stories_total.nil?
      return false if @num_epics_unstarted.nil?
      return false if @num_epics_in_progress.nil?
      return false if @num_points_unstarted.nil?
      return false if @num_stories_unestimated.nil?
      return false if @num_points_in_progress.nil?
      return false if @num_epics_total.nil?
      return false if @num_stories_completed.nil?
      return false if @num_points_completed.nil?
      return false if @num_points_total.nil?
      return false if @num_stories_in_progress.nil?
      return false if @num_epics_completed.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          num_related_documents == o.num_related_documents &&
          num_epics == o.num_epics &&
          num_stories_unstarted == o.num_stories_unstarted &&
          num_stories_total == o.num_stories_total &&
          num_epics_unstarted == o.num_epics_unstarted &&
          num_epics_in_progress == o.num_epics_in_progress &&
          num_points_unstarted == o.num_points_unstarted &&
          num_stories_unestimated == o.num_stories_unestimated &&
          num_points_in_progress == o.num_points_in_progress &&
          num_epics_total == o.num_epics_total &&
          num_stories_completed == o.num_stories_completed &&
          num_points_completed == o.num_points_completed &&
          num_points_total == o.num_points_total &&
          num_stories_in_progress == o.num_stories_in_progress &&
          num_epics_completed == o.num_epics_completed
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [num_related_documents, num_epics, num_stories_unstarted, num_stories_total, num_epics_unstarted, num_epics_in_progress, num_points_unstarted, num_stories_unestimated, num_points_in_progress, num_epics_total, num_stories_completed, num_points_completed, num_points_total, num_stories_in_progress, num_epics_completed].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Shortcut.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
