=begin
#Shortcut API

#Shortcut API

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.35
=end

require 'date'

module Shortcut
  class Task
    # Full text of the Task.
    attr_accessor :description

    # A string description of this resource.
    attr_accessor :entity_type

    # The unique identifier of the parent Story.
    attr_accessor :story_id

    # Deprecated: use member_mention_ids.
    attr_accessor :mention_ids

    # An array of UUIDs of Members mentioned in this Task.
    attr_accessor :member_mention_ids

    # The time/date the Task was completed.
    attr_accessor :completed_at

    # The time/date the Task was updated.
    attr_accessor :updated_at

    # An array of UUIDs of Groups mentioned in this Task.
    attr_accessor :group_mention_ids

    # An array of UUIDs of the Owners of this Task.
    attr_accessor :owner_ids

    # This field can be set to another unique ID. In the case that the Task has been imported from another tool, the ID in the other tool can be indicated here.
    attr_accessor :external_id

    # The unique ID of the Task.
    attr_accessor :id

    # The number corresponding to the Task's position within a list of Tasks on a Story.
    attr_accessor :position

    # True/false boolean indicating whether the Task has been completed.
    attr_accessor :complete

    # The time/date the Task was created.
    attr_accessor :created_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'description' => :'description',
        :'entity_type' => :'entity_type',
        :'story_id' => :'story_id',
        :'mention_ids' => :'mention_ids',
        :'member_mention_ids' => :'member_mention_ids',
        :'completed_at' => :'completed_at',
        :'updated_at' => :'updated_at',
        :'group_mention_ids' => :'group_mention_ids',
        :'owner_ids' => :'owner_ids',
        :'external_id' => :'external_id',
        :'id' => :'id',
        :'position' => :'position',
        :'complete' => :'complete',
        :'created_at' => :'created_at'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'description' => :'Object',
        :'entity_type' => :'Object',
        :'story_id' => :'Object',
        :'mention_ids' => :'Object',
        :'member_mention_ids' => :'Object',
        :'completed_at' => :'Object',
        :'updated_at' => :'Object',
        :'group_mention_ids' => :'Object',
        :'owner_ids' => :'Object',
        :'external_id' => :'Object',
        :'id' => :'Object',
        :'position' => :'Object',
        :'complete' => :'Object',
        :'created_at' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'completed_at',
        :'updated_at',
        :'external_id',
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shortcut::Task` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shortcut::Task`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      end

      if attributes.key?(:'story_id')
        self.story_id = attributes[:'story_id']
      end

      if attributes.key?(:'mention_ids')
        if (value = attributes[:'mention_ids']).is_a?(Array)
          self.mention_ids = value
        end
      end

      if attributes.key?(:'member_mention_ids')
        if (value = attributes[:'member_mention_ids']).is_a?(Array)
          self.member_mention_ids = value
        end
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'group_mention_ids')
        if (value = attributes[:'group_mention_ids']).is_a?(Array)
          self.group_mention_ids = value
        end
      end

      if attributes.key?(:'owner_ids')
        if (value = attributes[:'owner_ids']).is_a?(Array)
          self.owner_ids = value
        end
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'position')
        self.position = attributes[:'position']
      end

      if attributes.key?(:'complete')
        self.complete = attributes[:'complete']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @entity_type.nil?
        invalid_properties.push('invalid value for "entity_type", entity_type cannot be nil.')
      end

      if @story_id.nil?
        invalid_properties.push('invalid value for "story_id", story_id cannot be nil.')
      end

      if @mention_ids.nil?
        invalid_properties.push('invalid value for "mention_ids", mention_ids cannot be nil.')
      end

      if @member_mention_ids.nil?
        invalid_properties.push('invalid value for "member_mention_ids", member_mention_ids cannot be nil.')
      end

      if @completed_at.nil?
        invalid_properties.push('invalid value for "completed_at", completed_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @group_mention_ids.nil?
        invalid_properties.push('invalid value for "group_mention_ids", group_mention_ids cannot be nil.')
      end

      if @owner_ids.nil?
        invalid_properties.push('invalid value for "owner_ids", owner_ids cannot be nil.')
      end

      if @external_id.nil?
        invalid_properties.push('invalid value for "external_id", external_id cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @position.nil?
        invalid_properties.push('invalid value for "position", position cannot be nil.')
      end

      if @complete.nil?
        invalid_properties.push('invalid value for "complete", complete cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @description.nil?
      return false if @entity_type.nil?
      return false if @story_id.nil?
      return false if @mention_ids.nil?
      return false if @member_mention_ids.nil?
      return false if @completed_at.nil?
      return false if @updated_at.nil?
      return false if @group_mention_ids.nil?
      return false if @owner_ids.nil?
      return false if @external_id.nil?
      return false if @id.nil?
      return false if @position.nil?
      return false if @complete.nil?
      return false if @created_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          description == o.description &&
          entity_type == o.entity_type &&
          story_id == o.story_id &&
          mention_ids == o.mention_ids &&
          member_mention_ids == o.member_mention_ids &&
          completed_at == o.completed_at &&
          updated_at == o.updated_at &&
          group_mention_ids == o.group_mention_ids &&
          owner_ids == o.owner_ids &&
          external_id == o.external_id &&
          id == o.id &&
          position == o.position &&
          complete == o.complete &&
          created_at == o.created_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [description, entity_type, story_id, mention_ids, member_mention_ids, completed_at, updated_at, group_mention_ids, owner_ids, external_id, id, position, complete, created_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        Shortcut.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
