=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::CreateOrDeleteStoryReaction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Shortcut::CreateOrDeleteStoryReaction do
  let(:instance) { Shortcut::CreateOrDeleteStoryReaction.new }

  describe 'test an instance of CreateOrDeleteStoryReaction' do
    it 'should create an instance of CreateOrDeleteStoryReaction' do
      expect(instance).to be_instance_of(Shortcut::CreateOrDeleteStoryReaction)
    end
  end
  describe 'test attribute "emoji"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
