=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::CreateStoryLinkParams
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Shortcut::CreateStoryLinkParams do
  let(:instance) { Shortcut::CreateStoryLinkParams.new }

  describe 'test an instance of CreateStoryLinkParams' do
    it 'should create an instance of CreateStoryLinkParams' do
      expect(instance).to be_instance_of(Shortcut::CreateStoryLinkParams)
    end
  end
  describe 'test attribute "subject_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "verb"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["blocks", "duplicates", "relates to"])
      # validator.allowable_values.each do |value|
      #   expect { instance.verb = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "object_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
