=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::GetIterationStories
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Shortcut::GetIterationStories do
  let(:instance) { Shortcut::GetIterationStories.new }

  describe 'test an instance of GetIterationStories' do
    it 'should create an instance of GetIterationStories' do
      expect(instance).to be_instance_of(Shortcut::GetIterationStories)
    end
  end
  describe 'test attribute "includes_description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
