=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::MilestoneStats
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Shortcut::MilestoneStats do
  let(:instance) { Shortcut::MilestoneStats.new }

  describe 'test an instance of MilestoneStats' do
    it 'should create an instance of MilestoneStats' do
      expect(instance).to be_instance_of(Shortcut::MilestoneStats)
    end
  end
  describe 'test attribute "average_cycle_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "average_lead_time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "num_related_documents"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
