=begin
#Shortcut API

#Shortcut API

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.35
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::StoryStats
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StoryStats' do
  before do
    # run before each test
    @instance = Shortcut::StoryStats.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StoryStats' do
    it 'should create an instance of StoryStats' do
      expect(@instance).to be_instance_of(Shortcut::StoryStats)
    end
  end
  describe 'test attribute "num_related_documents"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
