=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::StoryHistoryChangeAddsRemovesInt
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Shortcut::StoryHistoryChangeAddsRemovesInt do
  let(:instance) { Shortcut::StoryHistoryChangeAddsRemovesInt.new }

  describe 'test an instance of StoryHistoryChangeAddsRemovesInt' do
    it 'should create an instance of StoryHistoryChangeAddsRemovesInt' do
      expect(instance).to be_instance_of(Shortcut::StoryHistoryChangeAddsRemovesInt)
    end
  end
  describe 'test attribute "adds"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "removes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
