=begin
#Shortcut API

#Shortcut API

The version of the OpenAPI document: 3.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Shortcut::UnusableEntitlementError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Shortcut::UnusableEntitlementError do
  let(:instance) { Shortcut::UnusableEntitlementError.new }

  describe 'test an instance of UnusableEntitlementError' do
    it 'should create an instance of UnusableEntitlementError' do
      expect(instance).to be_instance_of(Shortcut::UnusableEntitlementError)
    end
  end
  describe 'test attribute "reason_tag"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["entitlement-violation"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reason_tag = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "entitlement_tag"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
